board/urls.py
from django.urls import path

from .views import CommentList, PostCreate, PostDelete, PostEdit, PostList

app_name = "board"

urlpatterns = [
    path("", PostList.as_view(), name="post_list"),
    path("new", PostCreate.as_view(), name="post_add"),
    path("comments", CommentList.as_view(), name="comment_list"),
    path("<int:pk>/edit", PostEdit.as_view(), name="post_edit"),
    path("<int:pk>/delete", PostDelete.as_view(), name="post_delete"),
]

conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from ckeditor_uploader.views import upload as ckeditor_upload
from ckeditor_uploader.views import browse as ckeditor_browse
from django.views.decorators.cache import never_cache

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    # path("tinymce/", include("tinymce.urls")),
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("", include("board.urls")),
]

urlpatterns += [
    path(r"ckeditor/upload/", ckeditor_upload, name="ckeditor_upload"),
    path(r"ckeditor/browse/", never_cache(ckeditor_browse), name="ckeditor_browse"),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=256, unique=True)
    subscribers = models.ManyToManyField(Author, related_name="categories", blank=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    content = RichTextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=256)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def get_absolute_url(self) -> str:
        return reverse("board:post_edit", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        if len(self.title) > 32:
            return self.title[:32] + "..."
        else:
            return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    is_ack = models.BooleanField(default=False)

board/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from .models import Category, Comment, Post


class PostEditForm(forms.ModelForm):
    title = forms.CharField(
        label="",
        widget=forms.TextInput(),
    )
    category = forms.ModelChoiceField(
        label="",
        queryset=Category.objects.all(),
        required=True,
    )
    content = forms.CharField(
        label="",
        widget=CKEditorUploadingWidget(),
        required=True,
    )

    class Meta:
        model = Post
        fields = [
            "title",
            "category",
            "content",
        ]


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Ваш комментарий ..."}),
    )

    class Meta:
        model = Comment
        fields = ("text",)

board/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DeleteView, UpdateView

from .filters import CommentFilter, PostFilter
from .forms import CommentForm, PostEditForm
from .models import Author, Comment, Post


class PostList(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        queryset = Post.objects.all()
        filterset = PostFilter(request.GET, queryset)
        return render(
            request=request,
            template_name="board/post_list.html",
            context={
                "posts": filterset.qs,
                "comment_form": CommentForm,
                "filterset": filterset,
            },
            status=200,
        )

    def post(self, request: HttpResponse) -> HttpResponse:
        if "submit_comment_form" in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment: Comment = comment_form.save(commit=False)
                user = User.objects.filter(pk=request.user.pk).first()
                author = Author.objects.filter(user=user).first()
                if author is None or user is None:
                    raise Http404("Пользователь не найден")

                post_id = request.POST.get("post_id")
                if post_id is None:
                    raise Http404("Неизвестный пост")
                post = Post.objects.filter(pk=post_id).first()
                if post is None:
                    raise Http404("Пост не найден")

                comment.author = author
                comment.post = post
                comment.save()

        return redirect(reverse("board:post_list"))


class PostEdit(LoginRequiredMixin, UpdateView):
    form_class = PostEditForm
    model = Post
    template_name = "board/post_edit.html"
    success_url = reverse_lazy("board:post_list")


class PostCreate(LoginRequiredMixin, View):
    def get(self, request):
        return render(
            request=request,
            template_name="board/post_edit.html",
            context={"form": PostEditForm},
            status=200,
        )

    def post(self, request):
        user = User.objects.filter(pk=request.user.pk).first()
        author = Author.objects.filter(user=user).first()
        if author is None or user is None:
            raise Http404("Пользователь не найден")

        form = PostEditForm(request.POST)
        if form.is_valid():
            post: Post = form.save(commit=False)
            post.author = author
            post.save()
            return redirect(reverse("board:post_list"))
        else:
            return render(
                request=request,
                template_name="board/post_edit.html",
                context={"form": form},
                status=200,
            )


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "board/post_delete.html"
    success_url = reverse_lazy("board:post_list")
    context_object_name = "post"

    def get_object(self) -> Post:
        user = User.objects.filter(pk=self.request.user.pk).first()
        author = Author.objects.filter(user=user).first()
        if author is None or user is None:
            raise Http404("Пользователь не найден")

        pk = self.kwargs.get("pk")
        if not pk:
            raise Http404("Неизвестный идентификатор поста")
        obj = Post.objects.filter(author=author, pk=pk).first()
        if obj:
            return obj
        else:
            raise Http404("Пост не найден")


class CommentList(LoginRequiredMixin, View):
    def get(self, request):
        user = User.objects.filter(pk=request.user.pk).first()
        author = Author.objects.filter(user=user).first()
        if author is None or user is None:
            raise Http404("Пользователь не найден")

        queryset = Comment.objects.filter(post__author=author)
        filterset = CommentFilter(author.pk, request.GET, queryset)
        return render(
            request=request,
            template_name="board/comment_list.html",
            context={
                "comments": filterset.qs,
                "filterset": filterset,
            },
            status=200,
        )

    def post(self, request):
        if "_delete" in request.POST:
            pk = request.POST.get("_delete")
            if pk:
                comment: Comment = Comment.objects.filter(pk=int(pk)).first()
                if comment:
                    comment.delete()
        elif "_ack" in request.POST:
            pk = request.POST.get("_ack")
            if pk:
                comment: Comment = Comment.objects.filter(pk=int(pk)).first()
                if comment:
                    comment.is_ack = True
                    comment.save()
        return redirect(request.get_full_path())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/bootstrap.min.css' %} rel="stylesheet" />
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Доска объявлений</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% with request.resolver_match.url_name as url_name %}
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'post_list' %}active{% endif %}" href={% url 'board:post_list' %}>Список постов</a>
                            </li>
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link {% if url_name == 'post_add' %}active{% endif %}" href={% url 'board:post_add' %}>Новый пост</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% if url_name == 'comment_list' %}active{% endif %}" href={% url 'board:comment_list' %}>Комментарии</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% if url_name == 'account_logout' %}active{% endif %}" href={% url 'account_logout' %}>Выход</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link {% if url_name == 'account_login' %}active{% endif %}" href={% url 'account_login' %}>Вход</a>
                                </li>
                            {% endif %}
                        {% endwith %}
                    </ul>
                </div>
            </div>
        </nav>

        {% include 'board/inc/messages.html' %}
        {% block content %}
        <br>
        {% endblock content %}
        
        <script src={% static 'js/jquery-3.5.1.slim.min.js' %}></script>
        <script src={% static 'js/bootstrap.min.js' %}></script>
        <script src={% static 'js/bootstrap.bundle.min.js' %}></script>
        <script src={% static 'js/scripts.js' %}></script>
    </body>
    </html>
    

templates/board/comment_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mb-4, mt-4">
            <div class="card-header">
                <div>Фильтр комментариев</div>
            </div>
            <div class="card-body">
                <form action="" method="get">
                    {{ filterset.form|crispy }}
                    <input class="btn btn-success" type="submit" value="Поиск"/>
                    <a class="btn btn-warning" href="{% url 'board:comment_list' %}">Сбросить</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% for comment in comments %}
    <br>
    {% include "board/inc/comment_card.html" with comment=comment %}
{% endfor %}


{% endblock content %}

templates/board/inc/comment_card.html
{% load crispy_forms_tags %}

<div class="row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col">
                        <div>Пост: <b>{{ comment.post.title }}</b></div>
                    </div>
                    <div class="col text-right">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-dark btn-sm {% if comment.is_ack %}disabled{% endif %}" name="_ack" value="{{ comment.pk }}">
                                <span aria-hidden="true">Принять</span>
                            </button>
                            <button type="submit" class="btn btn-outline-dark btn-sm" name="_delete" value="{{ comment.pk }}">
                                <span aria-hidden="true">Удалить</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p class="mb-0"><b>{{ comment.author.user.email }}</b> написал {{ comment.create_time|timesince}} назад:</p>
                <p class="mb-0">{{ comment.text }}</p>
            </div>
        </div>
    </div>
</div>

templates/board/inc/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

templates/board/inc/post_card.html
{% load crispy_forms_tags %}

<div class="row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col">
                        <div><b>{{ post.author.user.email }}</b> - {{ post.create_time|timesince}} назад.</div>
                        <div>Категория: <a href="#"><span class="badge rounded-pill bg-secondary">{{ post.category }}</span></a></div>
                    </div>
                    <div class="col text-right">
                        {% if request.user == post.author.user %}
                            <a href={% url 'board:post_edit' post.id %} class="btn btn-outline-dark btn-sm"><span style="font-size:small">Править</span></a>
                            <a href={% url 'board:post_delete' post.id %} class="btn btn-outline-dark btn-sm"><span style="font-size:small">Удалить</span></a>
                        {% endif %}
                    </div>
                </div>
            
            </div>
            <div class="card-body">
                <h2 class="text-center">{{ post.title|safe }}</h2>
                <p>{{ post.content|safe }}</p>
                <i class="bi bi-chat-text"></i>
            </div>

            {% for comment in post.comments.all %}
                <div class="card mb-4 ml-4 mr-4">
                    <div class="card-header">
                        <p class="mb-0"><b>{{ comment.author.user.email }}</b> написал {{ comment.create_time|timesince}} назад:</p>
                        <p class="mb-0">{{ comment.text }}</p>
                        <i class="bi bi-chat-text"></i>
                    </div>   
                </div>    
            {% endfor %}

            {% if user.is_authenticated %}
                <div class="card mb-4 ml-4 mr-4" style="border-width: 0px">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{ post.id }}>
                        {{ comment_form|crispy }}
                        <button type="submit" name="submit_comment_form" class="btn btn-outline-primary btn-sm">Оставить комментарий</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/board/post_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <div class="card mb-4 mt-4">
                <div class="card-header">
                    <div><h2>{{ post.title }}</h2></div>
                </div>
                <div class="card-body">
                    <div>Будет удален.</div>
                    <form action="" method="post">
                        {% csrf_token %}
                        <a class="btn btn-success" href="{% url 'board:post_list' %}">Cancel</a>
                        <input class="btn btn-danger" type="submit" value="Delete"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/board/post_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mb-4 mt-4">
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}
                    <input class="btn btn-success" type="submit" value="Save"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/board/post_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mb-4, mt-4">
            <div class="card-header">
                <div>Фильтр постов</div>
            </div>
            <div class="card-body">
                <form action="" method="get">
                    {{ filterset.form|crispy }}
                    <input class="btn btn-success" type="submit" value="Поиск"/>
                    <a class="btn btn-warning" href="{% url 'board:post_list' %}">Сбросить</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% for post in posts %}
    <br>
    {% include "board/inc/post_card.html" with post=post %}
{% endfor %}


{% endblock content %}